mysqlPath: 
  shufujia: 47.111.165.32:3306
  fengze: 47.111.165.32:3305
  oupai: 47.111.165.32:3309
spring:
  datasource:
    softhome:
      jdbcUrl: jdbc:mysql://47.111.165.32:3306/softhome?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false
      username: root
      password: Leijun001
      driverClassName: com.mysql.cj.jdbc.Driver
