mysqlPath: 
  shufujia: 47.111.165.32:3306
  fengze: 47.111.165.32:3305
  oupai: 47.111.165.32:3309
hikari:
  default-datasource: shufujia
  datasource-map:
    shufujia:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.111.165.32:3306/softhome-rewrite?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&verifyServerCertificate=false
      username: root
      password: Leijun001
    
    
 
